export const nextTemplate = {
  //* Next.js Config (TypeScript)
  "next.config.ts": `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;`,

  //* PostCSS Config
  "postcss.config.js": `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`,

  //* Tailwind CSS Config (TypeScript)
  "tailwind.config.ts": `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {},
      fontFamily: {},
    },
  },
  plugins: [],
}
export default config`,

  //* README File
  "README.md": `# Next.js + TypeScript + Tailwind CSS Starter

This is a starter template for a Next.js project with TypeScript and Tailwind CSS.

## Getting Started

\`\`\`bash
npm run dev
# or
yarn dev
# or
pnpm dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.
`,

  //* Global CSS File (Next.js convention)
  "src/app/globals.css": `@import 'animations.css';
@tailwind base;
@tailwind components;
@tailwind utilities;`,

  //* Layout Component (Required for App Router)
  "src/app/layout.tsx": `import './globals.css'

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by devSeed CLI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`,

  //* Home Page Component
  "src/app/page.tsx": `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to Next.js!</h1>
      <p className="mt-4 text-xl">Built with TypeScript and Tailwind CSS</p>
    </main>
  )
}`,
};
